/* idx eng kor step */



INSERT INTO TBL_JAVAWORLD 
	   VALUES(1,'public','공공의',1);
INSERT INTO TBL_JAVAWORLD 
       VALUES(2,'private','개인적인',1);
INSERT INTO TBL_JAVAWORLD 
       VALUES(3,'iterate','반복하다',2);
INSERT INTO TBL_JAVAWORLD 
	   VALUES(4,'collection','수집',1);
INSERT INTO TBL_JAVAWORLD
       VALUES(5,'application','응용프로그램',3);
INSERT INTO TBL_JAVAWORLD
       VALUES(6,'binary','2인수의',2);
	

SELECT *
FROM TBL_JAVAWORLD
WHERE STEP = 1;


ALTER TABLE TBL_JAVAWORLD MODIFY idx NUMBER(8) NOT NULL PRIMARY key;
ALTER TABLE TBL_JAVAWORLD MODIFY english VARCHAR2(100) NOT NULL UNIQUE;
ALTER TABLE TBL_JAVAWORLD MODIFY korean NVARCHAR2(100) NOT NULL;
ALTER TABLE TBL_JAVAWORLD MODIFY step NUMBER(4) NULL CHECK (STEP<=4);

SELECT * 
FROM TBL_JAVAWORLD
ORDER BY IDX;

WHERE STEP = (SELECT IDX
			  FROM TBL_JAVAWORLD
			  WHERE IDX = 2)	
ORDER BY IDX ;
UPDATE TBL_JAVAWORLD SET IDX =7
WHERE IDX =5;
INSERT INTO TBL_JAVAWORLD VALUES(5,'constraint','제약사향',3);
INSERT INTO TBL_JAVAWORLD VALUES(9,'order','순서',1);
	  FROM DUAL;


-- idx 값이 2,5,9 인것만 조회 (IN)
SELECT * FROM TBL_JAVAWORLD 
WHERE IDX =2 OR IDX=5 OR IDX=9;

SELECT * FROM TBL_JAVAWORLD 
WHERE IDX IN(2,5,9);

--idx 값이 2~5 조회

SELECT * FROM TBL_JAVAWORLD 
WHERE IDX >=2 AND IDX <=5;

SELECT * FROM TBL_JAVAWORLD
WHERE IDX BETWEEN 2 AND 5;

--SELECT 컬럼명1, 컬럼명2,... FROM 테이블명
--[WHERE 컬럼명 = 값]
SELECT IDX ||' '|| ENGLISH  
	AS IDXeng 
  FROM TBL_JAVAWORLD 
 ORDER BY IDX ASC;

