/* idx eng kor step */



INSERT INTO TBL_JAVAWORLD 
	   VALUES(1,'public','공공의',1);
INSERT INTO TBL_JAVAWORLD 
       VALUES(2,'private','개인적인',1);
INSERT INTO TBL_JAVAWORLD 
       VALUES(3,'iterate','반복하다',2);
INSERT INTO TBL_JAVAWORLD 
	   VALUES(4,'collection','수집',1);
INSERT INTO TBL_JAVAWORLD
       VALUES(5,'application','응용프로그램',3);
INSERT INTO TBL_JAVAWORLD
       VALUES(6,'binary','2인수의',2);
	

SELECT *
FROM TBL_JAVAWORLD
WHERE STEP = 1;


ALTER TABLE TBL_JAVAWORLD MODIFY idx NUMBER(8) NOT NULL PRIMARY key;
ALTER TABLE TBL_JAVAWORLD MODIFY english VARCHAR2(100) NOT NULL UNIQUE;
ALTER TABLE TBL_JAVAWORLD MODIFY korean NVARCHAR2(100) NOT NULL;
ALTER TABLE TBL_JAVAWORLD MODIFY step NUMBER(4) NULL CHECK (STEP<=4);

SELECT * 
FROM TBL_JAVAWORLD 
WHERE STEP = (SELECT IDX
			  FROM TBL_JAVAWORLD
			  WHERE IDX = 2)	
ORDER BY IDX ;



